"""empty message

Revision ID: 0fb08f53a461
Revises: fa5b4f15a88c
Create Date: 2017-02-28 16:18:06.957474

"""

# revision identifiers, used by Alembic.
revision = '0fb08f53a461'
down_revision = 'fa5b4f15a88c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organisations')
    # ### end Alembic commands ###
