"""empty message

Revision ID: 454530372bf3
Revises: 6efc80b0433a
Create Date: 2017-03-01 10:33:33.435756

"""

# revision identifiers, used by Alembic.
revision = '454530372bf3'
down_revision = '6efc80b0433a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('cycle_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'reportingcycles', ['cycle_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'cycle_id')
    # ### end Alembic commands ###
