"""empty message

Revision ID: 6efc80b0433a
Revises: 7286f30b3c07
Create Date: 2017-03-01 10:08:35.155907

"""

# revision identifiers, used by Alembic.
revision = '6efc80b0433a'
down_revision = '7286f30b3c07'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reportingcycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('cycle_type', sa.Text(), nullable=True),
    sa.Column('cycle_value', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.drop_table('reportingcycless')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reportingcycless',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('cycle_type', mysql.TEXT(), nullable=True),
    sa.Column('cycle_value', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='reportingcycless_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('reportingcycles')
    # ### end Alembic commands ###
