"""empty message

Revision ID: 7286f30b3c07
Revises: b6643b184eb4
Create Date: 2017-03-01 09:57:22.343470

"""

# revision identifiers, used by Alembic.
revision = '7286f30b3c07'
down_revision = 'b6643b184eb4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reportingcycless',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('cycle_type', sa.Text(), nullable=True),
    sa.Column('cycle_value', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reportingcycless')
    # ### end Alembic commands ###
