"""empty message

Revision ID: b6643b184eb4
Revises: 0fb08f53a461
Create Date: 2017-02-28 17:09:10.394138

"""

# revision identifiers, used by Alembic.
revision = 'b6643b184eb4'
down_revision = '0fb08f53a461'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisations', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'organisations', 'users', ['admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organisations', type_='foreignkey')
    op.drop_column('organisations', 'admin_id')
    # ### end Alembic commands ###
